export const AUTH = "AUTH";
export const FINISHED = "FINISHED";
export const LOCATION_GATHER = "LOCATION_GATHER";
export const ACCOUNT_TYPE = "ACCOUNT_TYPE";
export const DIAGNOSTICS = "DIAGNOSTICS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const PUSH_NOTIFICATION = "PUSH_NOTIFICATION";